name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Super-Linter
        uses: github/super-linter@v4

        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Changelog_info file
        run: |
          git config --get remote.origin.url
          git clone https://github.com/Julesfogue/githubactions1.git
          git log --oneline
          git log
          git log --stat
          git log --pretty=oneline > changelog_info
          pwd
          cat changelog_info
          
      
